import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'sonner';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Order Management',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
                <header style={{ padding: '1rem', borderBottom: '1px solid #ddd' }}>
          <nav style={{ display: 'flex', gap: '1rem' }}>
            <a href="/">Home</a>
            <a href="/quotes">Quotes</a>
          </nav>
        </header>
        {children}
        <Toaster />
      </body>
    </html>
  )
}
