CREATE TABLE customers (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    tier VARCHAR(20) NOT NULL DEFAULT 'BASIC' CHECK (tier IN ('BASIC', 'PREMIUM')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
