server.port=8080
spring.application.name=order-service

# Default to H2 in-memory database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:org.h2.Driver}

# H2 Console
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console

# JPA settings
spring.jpa.hibernate.ddl-auto=validate

# Flyway
spring.flyway.enabled=true

